use BDEXam;

/**task1**/
--вторым по успешности в регионе
--Eastern: 106
--Western: 108
SELECT * FROM(SELECT CUST, REP, NAME, REGION, SUM(QTY * AMOUNT) AS SUM, ROW_NUMBER() OVER(PARTITION BY REGION ORDER BY SUM(QTY * AMOUNT) DESC) AS REP_NUMB
FROM ORDERS
INNER JOIN SALESREPS ON ORDERS.REP = SALESREPS.EMPL_NUM
INNER JOIN OFFICES ON OFFICES.OFFICE = SALESREPS.REP_OFFICE 
GROUP BY CUST, REP, REGION, NAME) TASK1
WHERE REP_NUMB = 2

/**task2**/
SELECT *, 100 - (QTY * 100/SUCCESSFUL) AS PERCENTS
FROM
--сумма продаж
(SELECT CUST, REP, REGION, SUM(QTY * AMOUNT) AS QTY,
--самая большая сумма продаж (1 сотрудника)
FIRST_VALUE(SUM(QTY * AMOUNT)) OVER(PARTITION BY REGION ORDER BY SUM(QTY * AMOUNT) DESC) AS SUCCESSFUL
FROM ORDERS
INNER JOIN SALESREPS ON ORDERS.REP = SALESREPS.EMPL_NUM
INNER JOIN OFFICES ON OFFICES.OFFICE = SALESREPS.REP_OFFICE 
GROUP by CUST, REP, REGION) TASK2

/**task4**/
SELECT ORDER_NUM, ORDER_DATE, REP, QTY, AMOUNT, LAG(AMOUNT) OVER(ORDER BY ORDER_DATE) AS PREVIOUS,
AMOUNT - LAG(AMOUNT) OVER(ORDER BY ORDER_DATE) AS DIFFERENCE
FROM ORDERS
WHERE ORDER_DATE > '2007-09-01'